name: CI - Run Unit Tests # Workflow name

on: # Define the events that trigger this workflow
  push: # Trigger workflow on push events
    branches: 
      - main # Trigger only for the 'main' branch
  pull_request: # Trigger workflow on pull request events
    branches:
      - main # Trigger only for pull requests targeting the 'main' branch

jobs:
  test: # Define a job named 'test'
    runs-on: ubuntu-latest # Specify the runner operating system for the job

    steps:
      - name: Check out repository code # Step to clone the repository to the runner
        uses: actions/checkout@v3 # Use the GitHub Actions checkout action (version 3)

      - name: Set up Python environment # Step to set up Python for the runner
        uses: actions/setup-python@v4 # Use the GitHub Actions setup-python action (version 4)
        with:
          python-version: '3.12' # Specify the Python version to use (3.12)

      - name: Install dependencies # Step to install project dependencies
        run: |
          python -m pip install --upgrade pip # Upgrade pip to the latest version

      - name: Run tests # Step to execute unit tests
        run: |
          python SudokuTests.py 
      
